name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub
    - name: Run script and update README
      run: |
        python script.py > lines.txt
        LINES=$(cat lines.txt)
        echo "Total lines: $LINES" > README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
